# Generated by Django 3.2.7 on 2021-10-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional',
            field=models.TextField(blank=True),
        ),
    ]
