# Generated by Django 3.2.7 on 2021-10-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
